#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jun 12 14:59:23 CEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=Bliss_v2.1.2_(Chocapic13_Shaders_edit).zip
